import './globals.css'
import type { Metadata } from 'next'
import Sidebar from '../components/layout/Sidebar'
import FollowBar from '../components/layout/FollowBar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="h-screen bg-black">
      <div className="container h-full mx-auto xl:px-30 max-w-6xl">
        <div className="grid grid-cols-4 h-full">
          <Sidebar />
          <div className="col-span-3 lg:col-span-2 border-x border-neutral-800">
            {children} 
          </div>
          <FollowBar />
        </div>  
      </div>
    </div>
  )
}
